name: Deploy to Render

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Render Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RENDER_SERVICE_ID }}
          password: ${{ secrets.RENDER_API_KEY }}

      - name: Build Docker image
        run: |
          docker build -t house-price-prediction:latest .

      - name: Push Docker image to Render
        run: |
          docker tag house-price-prediction:latest registry.render.com/${{ secrets.RENDER_SERVICE_ID }}/house-price-prediction:latest
          docker push registry.render.com/${{ secrets.RENDER_SERVICE_ID }}/house-price-prediction:latest

      - name: Trigger Render deploy
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}
